import Head from "next/head"
import { trpc } from "@/utils/trpc"

export default function Admin() {
  const hello = trpc.hello.useQuery({ text: "krzysztof" })
  return (
    <>
      <Head>
        <title>KP DEV - CMS PLATFORM (Admin)</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Hello From Admin</h1>
        <p>{hello.data?.greeting}</p>
      </main>
    </>
  )
}
