import Head from "next/head"

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>KP DEV - CMS PLATFORM (DASHBOARD)</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Hello From Dashboard</h1>
      </main>
    </>
  )
}
